version: '3'

services:
  postgis:
    image: postgis/postgis:13-master
    container_name: deepgis_postgis
    restart: always
    environment:
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DEFAULT_ENCODING: "UTF8"
      DEFAULT_COLLATION: "id_ID.utf8"
      DEFAULT_CTYPE: "id_ID.utf8"
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ~/DeepGIS/postgis/data:/var/lib/postgresql/data

  geoserver:
    image: kartoza/geoserver:2.20.0
    user: root
    container_name: deepgis_geoserver
    restart: always
    ports:
      - ${GEOSERVER_ADMIN_PORT}:8080
    environment:
      TZ: Asia/Shanghai
      STABLE_EXTENSIONS: ""
      COMMUNITY_EXTENSIONS: ""
      SAMPLE_DATA: "false"

      DB_BACKEND: POSTGRES
      HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      GEOSERVER_DATA_DIR: /var/lib/geoserver_data

#      INITIAL_MEMORY: "512M"
#      MAXIMUM_MEMORY: "1500M"

      TOMCAT_USER: ${TOMCAT_USER}
      TOMCAT_PASSWORD: ${TOMCAT_PASSWORD}

    depends_on:
      - postgis
    volumes:
      - ~/DeepGIS/geoserver/data:/var/lib/geoserver_data
      - ~/DeepGIS/geoserver/settings:/settings

  pgadmin4:
    restart: always
    image: dpage/pgadmin4
    container_name: deepgis_pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgis

  deepgis:
    restart: always
    image: deepgis:0.1.2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VUE_APP_BASE_API: http://${SERVER_HOST}:${BACKEND_PORT}
        VUE_APP_BASE_GEOSERVER_URL: http://${SERVER_HOST}:${GEOSERVER_ADMIN_PORT}
    container_name: DeepGIS
    ports:
      - ${BACKEND_PORT}:8010
      - ${FRONTEND_PORT}:8080
    depends_on:
      - geoserver
    command: '/entrypoint.sh'
    volumes:
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock
      - ${DOCKER_BIN_PATH}:/usr/bin/docker
    environment:
      port: 8010
      postgis_db_host: postgis
      postgis_db_port: 5432
      postgis_db_user: ${POSTGRES_USER}
      postgis_db_passwd: ${GEOSERVER_ADMIN_PASSWORD}

      geoserver_url: http://geoserver:8080/geoserver
      geoserver_user: ${GEOSERVER_ADMIN_USER}
      geoserver_passwd: ${GEOSERVER_ADMIN_PASSWORD}

      DOCKER_BASE_URL: tcp://${DOCKER_HOST}:${DOCKER_PORT}
      DOCKER_CODE_SERVER_DIR: ${HOME}/code_server/

      VUE_APP_BASE_API: http://${SERVER_HOST}:${BACKEND_PORT}
      VUE_APP_BASE_GEOSERVER_URL: http://${SERVER_HOST}:${GEOSERVER_ADMIN_PORT}
networks:
  default:
    driver: bridge
